name: "Build Ubuntu"

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        os: ['ubuntu-latest']
        perl: [ '5.32', '5.30', '5.28' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpan JONASBN/Crypt-OpenSSL-X509-1.903.tar.gz
      - run: cpan Test::NoTabs Test::Pod Test::Pod::Coverage
      - run: cpanm --installdeps .
      - run: perl Makefile.PL
      - run: make test
